In [ ]:
import pandas as pd

df = pd.read_csv("../data/sample_etf_daily.csv", parse_dates=["date"])
df.info()

# 说明 df 是一个 pandas 的 DataFrame，也就是二维表格数据。

<class 'pandas.DataFrame'>
RangeIndex: 1566 entries, 0 to 1565
Data columns (total 9 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   date    1566 non-null   datetime64[us]
 1   symbol  1566 non-null   int64
 2   name    1566 non-null   str
 3   open    1566 non-null   float64
 4   high    1566 non-null   float64
 5   low     1566 non-null   float64
 6   close   1566 non-null   float64
 7   volume  1566 non-null   int64
 8   amount  1566 non-null   float64
dtypes: datetime64[us](1), float64(5), int64(2), str(1)
memory usage: 110.2 KB

In [29]:
df.head()
df.tail()

,date,symbol,name,open,high,low,close,volume,amount
1561,2024-12-30,510300,沪深300ETF,3.371,3.405,3.356,3.390,859489,2.913446e+06
1562,2024-12-30,511010,国债ETF,112.335,112.452,111.943,112.060,1339419,1.500948e+08
1563,2024-12-31,159915,创业板ETF,1.450,1.521,1.433,1.503,1331497,2.001776e+06
1564,2024-12-31,510300,沪深300ETF,3.386,3.411,3.301,3.325,2103328,6.994353e+06
1565,2024-12-31,511010,国债ETF,111.926,112.394,111.662,112.129,822709,9.224993e+07

In [69]:
df.describe()

,date,symbol,open,high,low,close,volume,amount,ret,diff,strategy_ret,ma20,ma60,vol20,equity
count,1565,1565.000000,1565.000000,1565.000000,1565.000000,1565.000000,1.565000e+03,1.565000e+03,1562.000000,1565.000000,1.564000e+03,1508.000000,1506.000000,1546.000000,1562.000000
mean,2024-01-01 03:14:08.817891,393891.076677,38.554937,38.684205,38.427359,38.556248,1.741377e+06,6.785253e+07,-0.000246,0.070229,3.969890e+06,38.547319,38.516869,14.414874,0.956746
min,2023-01-02 00:00:00,159915.000000,1.290000,1.320000,1.263000,1.296000,3.274630e+05,6.049655e+05,-0.048669,-110.995000,-5.050696e+05,1.340200,36.325750,10.234684,0.590971
25%,2023-07-03 00:00:00,159915.000000,2.401000,2.463000,2.351000,2.407000,1.109922e+06,3.623477e+06,-0.005048,-104.498000,-4.929738e+05,2.401200,38.193021,13.038715,0.872840
50%,2024-01-02 00:00:00,510300.000000,3.407000,3.458000,3.355000,3.402000,1.586771e+06,6.071307e+06,0.000081,0.643000,4.083529e+04,3.381225,38.478233,14.347911,0.993535
75%,2024-07-02 00:00:00,511010.000000,109.127000,109.374000,108.867000,109.134000,2.191002e+06,1.222929e+08,0.004479,103.904000,1.262531e+07,109.118800,38.811396,15.274132,1.014353
max,2024-12-31 00:00:00,511010.000000,112.847000,113.049000,112.480000,112.794000,5.692302e+06,5.786077e+08,0.055060,111.302000,1.808918e+07,112.189900,41.140650,35.103429,1.363885
std,NaN,165340.608468,50.557359,50.668344,50.449441,50.560509,8.355428e+05,1.043498e+08,0.012594,77.740848,6.973241e+06,50.544173,0.831134,2.327971,0.119394

In [ ]:
# 行列信息
df.shape

(1565, 16)

In [ ]:
# 具体列信息
df.dtypes

date            datetime64[us]
symbol                   int64
name                       str
open                   float64
high                   float64
low                    float64
close                  float64
volume                   int64
amount                 float64
ret                    float64
diff                   float64
strategy_ret           float64
ma20                   float64
ma60                   float64
vol20                  float64
equity                 float64
dtype: object

In [27]:
df["close"]

0         2.221
1         3.867
2       109.836
3         2.193
4         3.782
         ...
1561      3.390
1562    112.060
1563      1.503
1564      3.325
1565    112.129
Name: close, Length: 1566, dtype: float64

In [30]:
df[["date", "close", "volume"]]

           date    close   volume
0    2023-01-02    2.221  2527879
1    2023-01-02    3.867  1108127
2    2023-01-02  109.836  1443705
3    2023-01-03    2.193  3430138
4    2023-01-03    3.782  3701207
...         ...      ...      ...
1561 2024-12-30    3.390   859489
1562 2024-12-30  112.060  1339419
1563 2024-12-31    1.503  1331497
1564 2024-12-31    3.325  2103328
1565 2024-12-31  112.129   822709

[1566 rows x 3 columns]

In [31]:
df[df["symbol"]=="510300"]

Empty DataFrame
Columns: [date, symbol, name, open, high, low, close, volume, amount]
Index: []

In [32]:
df[(df["symbol"]=="510300")&(df["close"]>3.8)]

Empty DataFrame
Columns: [date, symbol, name, open, high, low, close, volume, amount]
Index: []

In [33]:
df = df.sort_values("date")

In [34]:
df = df.set_index("date")

In [35]:
df = df.reset_index()

In [ ]:
# 按索引筛选出 2024-01-01 到 2024-03-01 之间的数据行。
df.loc["2024-01-01":"2024-03-01"]

Empty DataFrame
Columns: [date, symbol, name, open, high, low, close, volume, amount]
Index: []

In [ ]:
# ret = close/lastClose - 1  pct_change就是这个意思
df["ret"]=df["close"].pct_change()

In [38]:
df["ret"]

0             NaN
1        0.741108
2       27.403413
3       -0.980034
4        0.724578
          ...
1561    -0.570206
1562    75.911462
1563    -0.970328
1564    -0.547970
1565    73.603460
Name: ret, Length: 1566, dtype: float64

In [ ]:
# diff() 的意思是：计算当前值和上一行值的差值。
df["diff"]=df["close"].diff()
df["diff"]

0           NaN
1         1.646
2       105.969
3      -107.643
4         1.589
         ...
1561     -1.933
1562    110.603
1563   -108.735
1564     -1.822
1565    110.626
Name: diff, Length: 1566, dtype: float64

In [44]:
df["amount"] = df["close"] * df["volume"]
df["amount"]

0       5.614419e+06
1       4.285127e+06
2       1.585708e+08
3       7.522293e+06
4       1.399796e+07
            ...
1561    1.555253e+06
1562    1.500953e+08
1563    6.993566e+06
1564    2.001240e+06
1565    9.224954e+07
Name: amount, Length: 1566, dtype: float64

In [ ]:
# 统计每一列有多少个缺失值
df.isna().sum()

date      0
symbol    0
name      0
open      0
high      0
low       0
close     0
volume    0
amount    0
ret       1
diff      1
dtype: int64

In [49]:
df = df.dropna()
df.isna().sum()

date      0
symbol    0
name      0
open      0
high      0
low       0
close     0
volume    0
amount    0
ret       0
diff      0
dtype: int64

In [51]:
# 填充缺失值为0
df = df.fillna(0)
# 用前一个值填充
df = df.ffill()

In [ ]:
# df["strategy_ret"] = df["symbol"] * df["ret"]
# shift 是什么含义 shift(1)   # 取上一行 shift(-1)  # 取下一行
df["strategy_ret"] = df["signal"].shift(1) * df["ret"]
df["strategy_ret"]

1                NaN
2       1.398396e+07
3      -5.008071e+05
4       1.158709e+05
5       1.429704e+07
            ...
1561   -2.909764e+05
1562    1.213938e+07
1563   -4.958475e+05
1564   -2.796291e+05
1565    1.177030e+07
Name: strategy_ret, Length: 1565, dtype: float64

In [57]:
df["ma20"]=df["close"].rolling(20).mean()
df["ma20"]

1            NaN
2            NaN
3            NaN
4            NaN
5            NaN
          ...
1561    35.48515
1562    41.01135
1563    41.00045
1564    35.45075
1565    40.98210
Name: ma20, Length: 1565, dtype: float64

In [58]:
df["ma60"]=df["close"].rolling(60).mean()
df["ma60"]

1             NaN
2             NaN
3             NaN
4             NaN
5             NaN
          ...
1561    38.958200
1562    38.970300
1563    37.169167
1564    37.171450
1565    38.983617
Name: ma60, Length: 1565, dtype: float64

In [59]:
df["vol20"]=df["ret"].rolling(20).std()
df["vol20"]

1             NaN
2             NaN
3             NaN
4             NaN
5             NaN
          ...
1561    30.807985
1562    33.081634
1563    33.158765
1564    33.433024
1565    35.103429
Name: vol20, Length: 1565, dtype: float64

In [ ]:
# cumprod() 的含义是累计连乘
df["equity"]=(1+df["ret"]).cumprod()
df["equity"]

1        1.741108
2       49.453399
3        0.987393
4        1.702837
5       49.411076
          ...
1561     0.656011
1562    50.454750
1563     1.497073
1564     0.676722
1565    50.485817
Name: equity, Length: 1565, dtype: float64

In [ ]:
# 按照哪一列来分组
df["ret"] = df.groupby("symbol")["close"].pct_change()
df["equity"] = (1 + df["ret"]).groupby(df["symbol"]).cumprod()
df[["symbol", "date", "close", "ret", "equity"]]

      symbol       date    close       ret    equity
1     510300 2023-01-02    3.867       NaN       NaN
2     511010 2023-01-02  109.836       NaN       NaN
3     159915 2023-01-03    2.193       NaN       NaN
4     510300 2023-01-03    3.782 -0.021981  0.978019
5     511010 2023-01-03  109.742 -0.000856  0.999144
...      ...        ...      ...       ...       ...
1561  159915 2024-12-30    1.457 -0.021491  0.664387
1562  511010 2024-12-30  112.060 -0.002519  1.020248
1563  510300 2024-12-31    3.325 -0.019174  0.859840
1564  159915 2024-12-31    1.503  0.031572  0.685363
1565  511010 2024-12-31  112.129  0.000616  1.020877

[1565 rows x 5 columns]

In [68]:
# transform的意思是  输入：每个 symbol 分组后的 close  输出：和原 df 一样长的一列结果
df["ma20"] = df.groupby("symbol")["close"].transform(lambda x: x.rolling(20).mean())
df[["ma20"]]

           ma20
1           NaN
2           NaN
3           NaN
4           NaN
5           NaN
...         ...
1561    1.45705
1562  111.96130
1563    3.48885
1564    1.46390
1565  111.99810

[1565 rows x 1 columns]

In [81]:
# agg() 的核心意思是：把多行数据压缩成统计结果。
summary = df.groupby("symbol").agg({
    "close":"mean",
    "volume":"sum",
    "amount":"sum"
    })
display(summary)

             close     volume        amount
symbol
159915    2.119893  918511173  1.935836e+09
510300    3.489764  887305431  3.106895e+09
511010  109.989285  919438169  1.011465e+11

In [82]:
df.groupby("symbol")["close"].agg(["mean", "max", "min", "std"])

              mean      max      min       std
symbol
159915    2.119893    2.991    1.296  0.386029
510300    3.489764    4.233    2.988  0.314344
511010  109.989285  112.794  106.528  1.286459

In [83]:
df.groupby("symbol").agg({
    "close": ["mean", "max", "min", "std"],
    "volume": ["sum", "mean"],
    "amount": ["sum", "mean"],
})

             close                                 volume                \
              mean      max      min       std        sum          mean
symbol
159915    2.119893    2.991    1.296  0.386029  918511173  1.762977e+06
510300    3.489764    4.233    2.988  0.314344  887305431  1.699819e+06
511010  109.989285  112.794  106.528  1.286459  919438169  1.761376e+06

              amount
                 sum          mean
symbol
159915  1.935836e+09  3.715617e+06
510300  3.106895e+09  5.951906e+06
511010  1.011465e+11  1.937672e+08

In [ ]:
# merge的意思是把两张表合并，on表示按照什么合并
# concat是拼接，上下拼接和左右拼接都可以
# join表示按照索引合并

price = pd.DataFrame({
    "symbol": ["510300", "159915"],
    "close": [3.8, 2.1],
})

info = pd.DataFrame({
    "symbol": ["510300", "159915"],
    "name": ["沪深300ETF", "创业板ETF"],
})

test = pd.merge(price, info, on="symbol")
test.head()

   symbol  close      name
0  510300    3.8  沪深300ETF
1  159915    2.1    创业板ETF